# Generated by Django 5.2.14 on 2026-05-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0006_remove_client_user_client_nom_client_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='partie_adverse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Partie Adverse'),
        ),
    ]
